with-expecter: true
dir: "mocks/{{.PackageName}}"
mockname: "Mock{{.InterfaceName}}"
outpkg: "mocks_{{.PackageName}}"
filename: "mock_{{.InterfaceName}}.go"
packages:
  github.com/tkasuz/s3local/internal/domain/bucket:
    interfaces:
      ServiceInterface:
  github.com/tkasuz/s3local/internal/domain/object:
    interfaces:
      ServiceInterface:
