// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks_object

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	database "github.com/tkasuz/s3local/internal/sqlc"

	object "github.com/tkasuz/s3local/internal/domain/object"
)

// MockServiceInterface is an autogenerated mock type for the ServiceInterface type
type MockServiceInterface struct {
	mock.Mock
}

type MockServiceInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockServiceInterface) EXPECT() *MockServiceInterface_Expecter {
	return &MockServiceInterface_Expecter{mock: &_m.Mock}
}

// DeleteObject provides a mock function with given fields: ctx, bucketName, key
func (_m *MockServiceInterface) DeleteObject(ctx context.Context, bucketName string, key string) error {
	ret := _m.Called(ctx, bucketName, key)

	if len(ret) == 0 {
		panic("no return value specified for DeleteObject")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, bucketName, key)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockServiceInterface_DeleteObject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteObject'
type MockServiceInterface_DeleteObject_Call struct {
	*mock.Call
}

// DeleteObject is a helper method to define mock.On call
//   - ctx context.Context
//   - bucketName string
//   - key string
func (_e *MockServiceInterface_Expecter) DeleteObject(ctx interface{}, bucketName interface{}, key interface{}) *MockServiceInterface_DeleteObject_Call {
	return &MockServiceInterface_DeleteObject_Call{Call: _e.mock.On("DeleteObject", ctx, bucketName, key)}
}

func (_c *MockServiceInterface_DeleteObject_Call) Run(run func(ctx context.Context, bucketName string, key string)) *MockServiceInterface_DeleteObject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockServiceInterface_DeleteObject_Call) Return(_a0 error) *MockServiceInterface_DeleteObject_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockServiceInterface_DeleteObject_Call) RunAndReturn(run func(context.Context, string, string) error) *MockServiceInterface_DeleteObject_Call {
	_c.Call.Return(run)
	return _c
}

// GetObject provides a mock function with given fields: ctx, bucketName, key
func (_m *MockServiceInterface) GetObject(ctx context.Context, bucketName string, key string) (database.Object, error) {
	ret := _m.Called(ctx, bucketName, key)

	if len(ret) == 0 {
		panic("no return value specified for GetObject")
	}

	var r0 database.Object
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (database.Object, error)); ok {
		return rf(ctx, bucketName, key)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) database.Object); ok {
		r0 = rf(ctx, bucketName, key)
	} else {
		r0 = ret.Get(0).(database.Object)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, bucketName, key)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockServiceInterface_GetObject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetObject'
type MockServiceInterface_GetObject_Call struct {
	*mock.Call
}

// GetObject is a helper method to define mock.On call
//   - ctx context.Context
//   - bucketName string
//   - key string
func (_e *MockServiceInterface_Expecter) GetObject(ctx interface{}, bucketName interface{}, key interface{}) *MockServiceInterface_GetObject_Call {
	return &MockServiceInterface_GetObject_Call{Call: _e.mock.On("GetObject", ctx, bucketName, key)}
}

func (_c *MockServiceInterface_GetObject_Call) Run(run func(ctx context.Context, bucketName string, key string)) *MockServiceInterface_GetObject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockServiceInterface_GetObject_Call) Return(_a0 database.Object, _a1 error) *MockServiceInterface_GetObject_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockServiceInterface_GetObject_Call) RunAndReturn(run func(context.Context, string, string) (database.Object, error)) *MockServiceInterface_GetObject_Call {
	_c.Call.Return(run)
	return _c
}

// GetObjectMetadata provides a mock function with given fields: ctx, bucketName, key
func (_m *MockServiceInterface) GetObjectMetadata(ctx context.Context, bucketName string, key string) (database.GetObjectMetadataRow, error) {
	ret := _m.Called(ctx, bucketName, key)

	if len(ret) == 0 {
		panic("no return value specified for GetObjectMetadata")
	}

	var r0 database.GetObjectMetadataRow
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (database.GetObjectMetadataRow, error)); ok {
		return rf(ctx, bucketName, key)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) database.GetObjectMetadataRow); ok {
		r0 = rf(ctx, bucketName, key)
	} else {
		r0 = ret.Get(0).(database.GetObjectMetadataRow)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, bucketName, key)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockServiceInterface_GetObjectMetadata_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetObjectMetadata'
type MockServiceInterface_GetObjectMetadata_Call struct {
	*mock.Call
}

// GetObjectMetadata is a helper method to define mock.On call
//   - ctx context.Context
//   - bucketName string
//   - key string
func (_e *MockServiceInterface_Expecter) GetObjectMetadata(ctx interface{}, bucketName interface{}, key interface{}) *MockServiceInterface_GetObjectMetadata_Call {
	return &MockServiceInterface_GetObjectMetadata_Call{Call: _e.mock.On("GetObjectMetadata", ctx, bucketName, key)}
}

func (_c *MockServiceInterface_GetObjectMetadata_Call) Run(run func(ctx context.Context, bucketName string, key string)) *MockServiceInterface_GetObjectMetadata_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockServiceInterface_GetObjectMetadata_Call) Return(_a0 database.GetObjectMetadataRow, _a1 error) *MockServiceInterface_GetObjectMetadata_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockServiceInterface_GetObjectMetadata_Call) RunAndReturn(run func(context.Context, string, string) (database.GetObjectMetadataRow, error)) *MockServiceInterface_GetObjectMetadata_Call {
	_c.Call.Return(run)
	return _c
}

// GetObjectMetadataByID provides a mock function with given fields: ctx, objectID
func (_m *MockServiceInterface) GetObjectMetadataByID(ctx context.Context, objectID int64) ([]database.GetObjectMetadataByObjectIDRow, error) {
	ret := _m.Called(ctx, objectID)

	if len(ret) == 0 {
		panic("no return value specified for GetObjectMetadataByID")
	}

	var r0 []database.GetObjectMetadataByObjectIDRow
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) ([]database.GetObjectMetadataByObjectIDRow, error)); ok {
		return rf(ctx, objectID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) []database.GetObjectMetadataByObjectIDRow); ok {
		r0 = rf(ctx, objectID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]database.GetObjectMetadataByObjectIDRow)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, objectID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockServiceInterface_GetObjectMetadataByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetObjectMetadataByID'
type MockServiceInterface_GetObjectMetadataByID_Call struct {
	*mock.Call
}

// GetObjectMetadataByID is a helper method to define mock.On call
//   - ctx context.Context
//   - objectID int64
func (_e *MockServiceInterface_Expecter) GetObjectMetadataByID(ctx interface{}, objectID interface{}) *MockServiceInterface_GetObjectMetadataByID_Call {
	return &MockServiceInterface_GetObjectMetadataByID_Call{Call: _e.mock.On("GetObjectMetadataByID", ctx, objectID)}
}

func (_c *MockServiceInterface_GetObjectMetadataByID_Call) Run(run func(ctx context.Context, objectID int64)) *MockServiceInterface_GetObjectMetadataByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockServiceInterface_GetObjectMetadataByID_Call) Return(_a0 []database.GetObjectMetadataByObjectIDRow, _a1 error) *MockServiceInterface_GetObjectMetadataByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockServiceInterface_GetObjectMetadataByID_Call) RunAndReturn(run func(context.Context, int64) ([]database.GetObjectMetadataByObjectIDRow, error)) *MockServiceInterface_GetObjectMetadataByID_Call {
	_c.Call.Return(run)
	return _c
}

// ListObjects provides a mock function with given fields: ctx, bucketName, marker, prefix, maxKeys
func (_m *MockServiceInterface) ListObjects(ctx context.Context, bucketName string, marker string, prefix string, maxKeys int64) ([]database.ListObjectsRow, error) {
	ret := _m.Called(ctx, bucketName, marker, prefix, maxKeys)

	if len(ret) == 0 {
		panic("no return value specified for ListObjects")
	}

	var r0 []database.ListObjectsRow
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, int64) ([]database.ListObjectsRow, error)); ok {
		return rf(ctx, bucketName, marker, prefix, maxKeys)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, int64) []database.ListObjectsRow); ok {
		r0 = rf(ctx, bucketName, marker, prefix, maxKeys)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]database.ListObjectsRow)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string, int64) error); ok {
		r1 = rf(ctx, bucketName, marker, prefix, maxKeys)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockServiceInterface_ListObjects_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListObjects'
type MockServiceInterface_ListObjects_Call struct {
	*mock.Call
}

// ListObjects is a helper method to define mock.On call
//   - ctx context.Context
//   - bucketName string
//   - marker string
//   - prefix string
//   - maxKeys int64
func (_e *MockServiceInterface_Expecter) ListObjects(ctx interface{}, bucketName interface{}, marker interface{}, prefix interface{}, maxKeys interface{}) *MockServiceInterface_ListObjects_Call {
	return &MockServiceInterface_ListObjects_Call{Call: _e.mock.On("ListObjects", ctx, bucketName, marker, prefix, maxKeys)}
}

func (_c *MockServiceInterface_ListObjects_Call) Run(run func(ctx context.Context, bucketName string, marker string, prefix string, maxKeys int64)) *MockServiceInterface_ListObjects_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string), args[4].(int64))
	})
	return _c
}

func (_c *MockServiceInterface_ListObjects_Call) Return(_a0 []database.ListObjectsRow, _a1 error) *MockServiceInterface_ListObjects_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockServiceInterface_ListObjects_Call) RunAndReturn(run func(context.Context, string, string, string, int64) ([]database.ListObjectsRow, error)) *MockServiceInterface_ListObjects_Call {
	_c.Call.Return(run)
	return _c
}

// PutObject provides a mock function with given fields: ctx, params
func (_m *MockServiceInterface) PutObject(ctx context.Context, params object.PutObjectParams) (database.CreateObjectRow, error) {
	ret := _m.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for PutObject")
	}

	var r0 database.CreateObjectRow
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, object.PutObjectParams) (database.CreateObjectRow, error)); ok {
		return rf(ctx, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, object.PutObjectParams) database.CreateObjectRow); ok {
		r0 = rf(ctx, params)
	} else {
		r0 = ret.Get(0).(database.CreateObjectRow)
	}

	if rf, ok := ret.Get(1).(func(context.Context, object.PutObjectParams) error); ok {
		r1 = rf(ctx, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockServiceInterface_PutObject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PutObject'
type MockServiceInterface_PutObject_Call struct {
	*mock.Call
}

// PutObject is a helper method to define mock.On call
//   - ctx context.Context
//   - params object.PutObjectParams
func (_e *MockServiceInterface_Expecter) PutObject(ctx interface{}, params interface{}) *MockServiceInterface_PutObject_Call {
	return &MockServiceInterface_PutObject_Call{Call: _e.mock.On("PutObject", ctx, params)}
}

func (_c *MockServiceInterface_PutObject_Call) Run(run func(ctx context.Context, params object.PutObjectParams)) *MockServiceInterface_PutObject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(object.PutObjectParams))
	})
	return _c
}

func (_c *MockServiceInterface_PutObject_Call) Return(_a0 database.CreateObjectRow, _a1 error) *MockServiceInterface_PutObject_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockServiceInterface_PutObject_Call) RunAndReturn(run func(context.Context, object.PutObjectParams) (database.CreateObjectRow, error)) *MockServiceInterface_PutObject_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockServiceInterface creates a new instance of MockServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockServiceInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockServiceInterface {
	mock := &MockServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
