// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks_bucket

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	database "github.com/tkasuz/s3local/internal/sqlc"
)

// MockServiceInterface is an autogenerated mock type for the ServiceInterface type
type MockServiceInterface struct {
	mock.Mock
}

type MockServiceInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockServiceInterface) EXPECT() *MockServiceInterface_Expecter {
	return &MockServiceInterface_Expecter{mock: &_m.Mock}
}

// CreateBucket provides a mock function with given fields: ctx, name, region
func (_m *MockServiceInterface) CreateBucket(ctx context.Context, name string, region string) error {
	ret := _m.Called(ctx, name, region)

	if len(ret) == 0 {
		panic("no return value specified for CreateBucket")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, name, region)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockServiceInterface_CreateBucket_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateBucket'
type MockServiceInterface_CreateBucket_Call struct {
	*mock.Call
}

// CreateBucket is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - region string
func (_e *MockServiceInterface_Expecter) CreateBucket(ctx interface{}, name interface{}, region interface{}) *MockServiceInterface_CreateBucket_Call {
	return &MockServiceInterface_CreateBucket_Call{Call: _e.mock.On("CreateBucket", ctx, name, region)}
}

func (_c *MockServiceInterface_CreateBucket_Call) Run(run func(ctx context.Context, name string, region string)) *MockServiceInterface_CreateBucket_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockServiceInterface_CreateBucket_Call) Return(_a0 error) *MockServiceInterface_CreateBucket_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockServiceInterface_CreateBucket_Call) RunAndReturn(run func(context.Context, string, string) error) *MockServiceInterface_CreateBucket_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteBucket provides a mock function with given fields: ctx, name
func (_m *MockServiceInterface) DeleteBucket(ctx context.Context, name string) error {
	ret := _m.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for DeleteBucket")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, name)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockServiceInterface_DeleteBucket_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteBucket'
type MockServiceInterface_DeleteBucket_Call struct {
	*mock.Call
}

// DeleteBucket is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockServiceInterface_Expecter) DeleteBucket(ctx interface{}, name interface{}) *MockServiceInterface_DeleteBucket_Call {
	return &MockServiceInterface_DeleteBucket_Call{Call: _e.mock.On("DeleteBucket", ctx, name)}
}

func (_c *MockServiceInterface_DeleteBucket_Call) Run(run func(ctx context.Context, name string)) *MockServiceInterface_DeleteBucket_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockServiceInterface_DeleteBucket_Call) Return(_a0 error) *MockServiceInterface_DeleteBucket_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockServiceInterface_DeleteBucket_Call) RunAndReturn(run func(context.Context, string) error) *MockServiceInterface_DeleteBucket_Call {
	_c.Call.Return(run)
	return _c
}

// GetBucket provides a mock function with given fields: ctx, name
func (_m *MockServiceInterface) GetBucket(ctx context.Context, name string) (database.Bucket, error) {
	ret := _m.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for GetBucket")
	}

	var r0 database.Bucket
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (database.Bucket, error)); ok {
		return rf(ctx, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) database.Bucket); ok {
		r0 = rf(ctx, name)
	} else {
		r0 = ret.Get(0).(database.Bucket)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockServiceInterface_GetBucket_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBucket'
type MockServiceInterface_GetBucket_Call struct {
	*mock.Call
}

// GetBucket is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockServiceInterface_Expecter) GetBucket(ctx interface{}, name interface{}) *MockServiceInterface_GetBucket_Call {
	return &MockServiceInterface_GetBucket_Call{Call: _e.mock.On("GetBucket", ctx, name)}
}

func (_c *MockServiceInterface_GetBucket_Call) Run(run func(ctx context.Context, name string)) *MockServiceInterface_GetBucket_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockServiceInterface_GetBucket_Call) Return(_a0 database.Bucket, _a1 error) *MockServiceInterface_GetBucket_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockServiceInterface_GetBucket_Call) RunAndReturn(run func(context.Context, string) (database.Bucket, error)) *MockServiceInterface_GetBucket_Call {
	_c.Call.Return(run)
	return _c
}

// ListBuckets provides a mock function with given fields: ctx
func (_m *MockServiceInterface) ListBuckets(ctx context.Context) ([]database.Bucket, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListBuckets")
	}

	var r0 []database.Bucket
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]database.Bucket, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []database.Bucket); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]database.Bucket)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockServiceInterface_ListBuckets_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListBuckets'
type MockServiceInterface_ListBuckets_Call struct {
	*mock.Call
}

// ListBuckets is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockServiceInterface_Expecter) ListBuckets(ctx interface{}) *MockServiceInterface_ListBuckets_Call {
	return &MockServiceInterface_ListBuckets_Call{Call: _e.mock.On("ListBuckets", ctx)}
}

func (_c *MockServiceInterface_ListBuckets_Call) Run(run func(ctx context.Context)) *MockServiceInterface_ListBuckets_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockServiceInterface_ListBuckets_Call) Return(_a0 []database.Bucket, _a1 error) *MockServiceInterface_ListBuckets_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockServiceInterface_ListBuckets_Call) RunAndReturn(run func(context.Context) ([]database.Bucket, error)) *MockServiceInterface_ListBuckets_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockServiceInterface creates a new instance of MockServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockServiceInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockServiceInterface {
	mock := &MockServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
