// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: bucket.sql

package db

import (
	"context"
)

const BucketExists = `-- name: BucketExists :one
SELECT COUNT(*) > 0 as bucket_exists
FROM buckets
WHERE name = ?
`

func (q *Queries) BucketExists(ctx context.Context, name string) (bool, error) {
	row := q.queryRow(ctx, q.bucketExistsStmt, BucketExists, name)
	var bucket_exists bool
	err := row.Scan(&bucket_exists)
	return bucket_exists, err
}

const CountObjectsInBucket = `-- name: CountObjectsInBucket :one
SELECT COUNT(*) as count
FROM objects
WHERE bucket_name = ?
`

func (q *Queries) CountObjectsInBucket(ctx context.Context, bucketName string) (int64, error) {
	row := q.queryRow(ctx, q.countObjectsInBucketStmt, CountObjectsInBucket, bucketName)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const CreateBucket = `-- name: CreateBucket :exec
INSERT INTO buckets (name, region)
VALUES (?, ?)
`

type CreateBucketParams struct {
	Name   string `json:"name"`
	Region string `json:"region"`
}

func (q *Queries) CreateBucket(ctx context.Context, arg CreateBucketParams) error {
	_, err := q.exec(ctx, q.createBucketStmt, CreateBucket, arg.Name, arg.Region)
	return err
}

const DeleteBucket = `-- name: DeleteBucket :exec
DELETE FROM buckets
WHERE name = ?
`

func (q *Queries) DeleteBucket(ctx context.Context, name string) error {
	_, err := q.exec(ctx, q.deleteBucketStmt, DeleteBucket, name)
	return err
}

const GetBucket = `-- name: GetBucket :one
SELECT name, region, created_at
FROM buckets
WHERE name = ?
`

func (q *Queries) GetBucket(ctx context.Context, name string) (Bucket, error) {
	row := q.queryRow(ctx, q.getBucketStmt, GetBucket, name)
	var i Bucket
	err := row.Scan(&i.Name, &i.Region, &i.CreatedAt)
	return i, err
}

const ListBuckets = `-- name: ListBuckets :many
SELECT name, region, created_at
FROM buckets
ORDER BY created_at ASC
`

func (q *Queries) ListBuckets(ctx context.Context) ([]Bucket, error) {
	rows, err := q.query(ctx, q.listBucketsStmt, ListBuckets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Bucket{}
	for rows.Next() {
		var i Bucket
		if err := rows.Scan(&i.Name, &i.Region, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
