// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"context"
	"database/sql"
	"fmt"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.bucketExistsStmt, err = db.PrepareContext(ctx, BucketExists); err != nil {
		return nil, fmt.Errorf("error preparing query BucketExists: %w", err)
	}
	if q.bucketPolicyExistsStmt, err = db.PrepareContext(ctx, BucketPolicyExists); err != nil {
		return nil, fmt.Errorf("error preparing query BucketPolicyExists: %w", err)
	}
	if q.copyObjectStmt, err = db.PrepareContext(ctx, CopyObject); err != nil {
		return nil, fmt.Errorf("error preparing query CopyObject: %w", err)
	}
	if q.countObjectsInBucketStmt, err = db.PrepareContext(ctx, CountObjectsInBucket); err != nil {
		return nil, fmt.Errorf("error preparing query CountObjectsInBucket: %w", err)
	}
	if q.createBucketStmt, err = db.PrepareContext(ctx, CreateBucket); err != nil {
		return nil, fmt.Errorf("error preparing query CreateBucket: %w", err)
	}
	if q.createBucketTagStmt, err = db.PrepareContext(ctx, CreateBucketTag); err != nil {
		return nil, fmt.Errorf("error preparing query CreateBucketTag: %w", err)
	}
	if q.createEventStmt, err = db.PrepareContext(ctx, CreateEvent); err != nil {
		return nil, fmt.Errorf("error preparing query CreateEvent: %w", err)
	}
	if q.createNotificationStmt, err = db.PrepareContext(ctx, CreateNotification); err != nil {
		return nil, fmt.Errorf("error preparing query CreateNotification: %w", err)
	}
	if q.createObjectStmt, err = db.PrepareContext(ctx, CreateObject); err != nil {
		return nil, fmt.Errorf("error preparing query CreateObject: %w", err)
	}
	if q.createObjectMetadataStmt, err = db.PrepareContext(ctx, CreateObjectMetadata); err != nil {
		return nil, fmt.Errorf("error preparing query CreateObjectMetadata: %w", err)
	}
	if q.createObjectTagStmt, err = db.PrepareContext(ctx, CreateObjectTag); err != nil {
		return nil, fmt.Errorf("error preparing query CreateObjectTag: %w", err)
	}
	if q.deleteAllObjectTagsStmt, err = db.PrepareContext(ctx, DeleteAllObjectTags); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteAllObjectTags: %w", err)
	}
	if q.deleteBucketStmt, err = db.PrepareContext(ctx, DeleteBucket); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteBucket: %w", err)
	}
	if q.deleteBucketPolicyStmt, err = db.PrepareContext(ctx, DeleteBucketPolicy); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteBucketPolicy: %w", err)
	}
	if q.deleteBucketTagStmt, err = db.PrepareContext(ctx, DeleteBucketTag); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteBucketTag: %w", err)
	}
	if q.deleteBucketTagsStmt, err = db.PrepareContext(ctx, DeleteBucketTags); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteBucketTags: %w", err)
	}
	if q.deleteNotificationStmt, err = db.PrepareContext(ctx, DeleteNotification); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteNotification: %w", err)
	}
	if q.deleteObjectStmt, err = db.PrepareContext(ctx, DeleteObject); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteObject: %w", err)
	}
	if q.deleteObjectMetadataStmt, err = db.PrepareContext(ctx, DeleteObjectMetadata); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteObjectMetadata: %w", err)
	}
	if q.deleteObjectTagsStmt, err = db.PrepareContext(ctx, DeleteObjectTags); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteObjectTags: %w", err)
	}
	if q.getBucketStmt, err = db.PrepareContext(ctx, GetBucket); err != nil {
		return nil, fmt.Errorf("error preparing query GetBucket: %w", err)
	}
	if q.getBucketPolicyStmt, err = db.PrepareContext(ctx, GetBucketPolicy); err != nil {
		return nil, fmt.Errorf("error preparing query GetBucketPolicy: %w", err)
	}
	if q.getBucketTagsStmt, err = db.PrepareContext(ctx, GetBucketTags); err != nil {
		return nil, fmt.Errorf("error preparing query GetBucketTags: %w", err)
	}
	if q.getNotificationStmt, err = db.PrepareContext(ctx, GetNotification); err != nil {
		return nil, fmt.Errorf("error preparing query GetNotification: %w", err)
	}
	if q.getObjectStmt, err = db.PrepareContext(ctx, GetObject); err != nil {
		return nil, fmt.Errorf("error preparing query GetObject: %w", err)
	}
	if q.getObjectByIDStmt, err = db.PrepareContext(ctx, GetObjectByID); err != nil {
		return nil, fmt.Errorf("error preparing query GetObjectByID: %w", err)
	}
	if q.getObjectIDStmt, err = db.PrepareContext(ctx, GetObjectID); err != nil {
		return nil, fmt.Errorf("error preparing query GetObjectID: %w", err)
	}
	if q.getObjectMetadataStmt, err = db.PrepareContext(ctx, GetObjectMetadata); err != nil {
		return nil, fmt.Errorf("error preparing query GetObjectMetadata: %w", err)
	}
	if q.getObjectMetadataByObjectIDStmt, err = db.PrepareContext(ctx, GetObjectMetadataByObjectID); err != nil {
		return nil, fmt.Errorf("error preparing query GetObjectMetadataByObjectID: %w", err)
	}
	if q.getObjectTagsStmt, err = db.PrepareContext(ctx, GetObjectTags); err != nil {
		return nil, fmt.Errorf("error preparing query GetObjectTags: %w", err)
	}
	if q.listBucketsStmt, err = db.PrepareContext(ctx, ListBuckets); err != nil {
		return nil, fmt.Errorf("error preparing query ListBuckets: %w", err)
	}
	if q.listBucketsFilteredStmt, err = db.PrepareContext(ctx, ListBucketsFiltered); err != nil {
		return nil, fmt.Errorf("error preparing query ListBucketsFiltered: %w", err)
	}
	if q.listEnabledNotificationsByBucketStmt, err = db.PrepareContext(ctx, ListEnabledNotificationsByBucket); err != nil {
		return nil, fmt.Errorf("error preparing query ListEnabledNotificationsByBucket: %w", err)
	}
	if q.listEventsByBucketStmt, err = db.PrepareContext(ctx, ListEventsByBucket); err != nil {
		return nil, fmt.Errorf("error preparing query ListEventsByBucket: %w", err)
	}
	if q.listNotificationsByBucketStmt, err = db.PrepareContext(ctx, ListNotificationsByBucket); err != nil {
		return nil, fmt.Errorf("error preparing query ListNotificationsByBucket: %w", err)
	}
	if q.listNotificationsByEventTypeStmt, err = db.PrepareContext(ctx, ListNotificationsByEventType); err != nil {
		return nil, fmt.Errorf("error preparing query ListNotificationsByEventType: %w", err)
	}
	if q.listObjectsStmt, err = db.PrepareContext(ctx, ListObjects); err != nil {
		return nil, fmt.Errorf("error preparing query ListObjects: %w", err)
	}
	if q.listObjectsWithDelimiterStmt, err = db.PrepareContext(ctx, ListObjectsWithDelimiter); err != nil {
		return nil, fmt.Errorf("error preparing query ListObjectsWithDelimiter: %w", err)
	}
	if q.listPendingNotificationJobsStmt, err = db.PrepareContext(ctx, ListPendingNotificationJobs); err != nil {
		return nil, fmt.Errorf("error preparing query ListPendingNotificationJobs: %w", err)
	}
	if q.objectExistsStmt, err = db.PrepareContext(ctx, ObjectExists); err != nil {
		return nil, fmt.Errorf("error preparing query ObjectExists: %w", err)
	}
	if q.putBucketPolicyStmt, err = db.PrepareContext(ctx, PutBucketPolicy); err != nil {
		return nil, fmt.Errorf("error preparing query PutBucketPolicy: %w", err)
	}
	if q.updateNotificationStmt, err = db.PrepareContext(ctx, UpdateNotification); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateNotification: %w", err)
	}
	if q.updateNotificationEnabledStmt, err = db.PrepareContext(ctx, UpdateNotificationEnabled); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateNotificationEnabled: %w", err)
	}
	if q.updateNotificationJobStatusStmt, err = db.PrepareContext(ctx, UpdateNotificationJobStatus); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateNotificationJobStatus: %w", err)
	}
	if q.updateObjectStmt, err = db.PrepareContext(ctx, UpdateObject); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateObject: %w", err)
	}
	return &q, nil
}

func (q *Queries) Close() error {
	var err error
	if q.bucketExistsStmt != nil {
		if cerr := q.bucketExistsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing bucketExistsStmt: %w", cerr)
		}
	}
	if q.bucketPolicyExistsStmt != nil {
		if cerr := q.bucketPolicyExistsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing bucketPolicyExistsStmt: %w", cerr)
		}
	}
	if q.copyObjectStmt != nil {
		if cerr := q.copyObjectStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing copyObjectStmt: %w", cerr)
		}
	}
	if q.countObjectsInBucketStmt != nil {
		if cerr := q.countObjectsInBucketStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing countObjectsInBucketStmt: %w", cerr)
		}
	}
	if q.createBucketStmt != nil {
		if cerr := q.createBucketStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createBucketStmt: %w", cerr)
		}
	}
	if q.createBucketTagStmt != nil {
		if cerr := q.createBucketTagStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createBucketTagStmt: %w", cerr)
		}
	}
	if q.createEventStmt != nil {
		if cerr := q.createEventStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createEventStmt: %w", cerr)
		}
	}
	if q.createNotificationStmt != nil {
		if cerr := q.createNotificationStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createNotificationStmt: %w", cerr)
		}
	}
	if q.createObjectStmt != nil {
		if cerr := q.createObjectStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createObjectStmt: %w", cerr)
		}
	}
	if q.createObjectMetadataStmt != nil {
		if cerr := q.createObjectMetadataStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createObjectMetadataStmt: %w", cerr)
		}
	}
	if q.createObjectTagStmt != nil {
		if cerr := q.createObjectTagStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createObjectTagStmt: %w", cerr)
		}
	}
	if q.deleteAllObjectTagsStmt != nil {
		if cerr := q.deleteAllObjectTagsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteAllObjectTagsStmt: %w", cerr)
		}
	}
	if q.deleteBucketStmt != nil {
		if cerr := q.deleteBucketStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteBucketStmt: %w", cerr)
		}
	}
	if q.deleteBucketPolicyStmt != nil {
		if cerr := q.deleteBucketPolicyStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteBucketPolicyStmt: %w", cerr)
		}
	}
	if q.deleteBucketTagStmt != nil {
		if cerr := q.deleteBucketTagStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteBucketTagStmt: %w", cerr)
		}
	}
	if q.deleteBucketTagsStmt != nil {
		if cerr := q.deleteBucketTagsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteBucketTagsStmt: %w", cerr)
		}
	}
	if q.deleteNotificationStmt != nil {
		if cerr := q.deleteNotificationStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteNotificationStmt: %w", cerr)
		}
	}
	if q.deleteObjectStmt != nil {
		if cerr := q.deleteObjectStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteObjectStmt: %w", cerr)
		}
	}
	if q.deleteObjectMetadataStmt != nil {
		if cerr := q.deleteObjectMetadataStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteObjectMetadataStmt: %w", cerr)
		}
	}
	if q.deleteObjectTagsStmt != nil {
		if cerr := q.deleteObjectTagsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteObjectTagsStmt: %w", cerr)
		}
	}
	if q.getBucketStmt != nil {
		if cerr := q.getBucketStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getBucketStmt: %w", cerr)
		}
	}
	if q.getBucketPolicyStmt != nil {
		if cerr := q.getBucketPolicyStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getBucketPolicyStmt: %w", cerr)
		}
	}
	if q.getBucketTagsStmt != nil {
		if cerr := q.getBucketTagsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getBucketTagsStmt: %w", cerr)
		}
	}
	if q.getNotificationStmt != nil {
		if cerr := q.getNotificationStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getNotificationStmt: %w", cerr)
		}
	}
	if q.getObjectStmt != nil {
		if cerr := q.getObjectStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getObjectStmt: %w", cerr)
		}
	}
	if q.getObjectByIDStmt != nil {
		if cerr := q.getObjectByIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getObjectByIDStmt: %w", cerr)
		}
	}
	if q.getObjectIDStmt != nil {
		if cerr := q.getObjectIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getObjectIDStmt: %w", cerr)
		}
	}
	if q.getObjectMetadataStmt != nil {
		if cerr := q.getObjectMetadataStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getObjectMetadataStmt: %w", cerr)
		}
	}
	if q.getObjectMetadataByObjectIDStmt != nil {
		if cerr := q.getObjectMetadataByObjectIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getObjectMetadataByObjectIDStmt: %w", cerr)
		}
	}
	if q.getObjectTagsStmt != nil {
		if cerr := q.getObjectTagsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getObjectTagsStmt: %w", cerr)
		}
	}
	if q.listBucketsStmt != nil {
		if cerr := q.listBucketsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listBucketsStmt: %w", cerr)
		}
	}
	if q.listBucketsFilteredStmt != nil {
		if cerr := q.listBucketsFilteredStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listBucketsFilteredStmt: %w", cerr)
		}
	}
	if q.listEnabledNotificationsByBucketStmt != nil {
		if cerr := q.listEnabledNotificationsByBucketStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listEnabledNotificationsByBucketStmt: %w", cerr)
		}
	}
	if q.listEventsByBucketStmt != nil {
		if cerr := q.listEventsByBucketStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listEventsByBucketStmt: %w", cerr)
		}
	}
	if q.listNotificationsByBucketStmt != nil {
		if cerr := q.listNotificationsByBucketStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listNotificationsByBucketStmt: %w", cerr)
		}
	}
	if q.listNotificationsByEventTypeStmt != nil {
		if cerr := q.listNotificationsByEventTypeStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listNotificationsByEventTypeStmt: %w", cerr)
		}
	}
	if q.listObjectsStmt != nil {
		if cerr := q.listObjectsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listObjectsStmt: %w", cerr)
		}
	}
	if q.listObjectsWithDelimiterStmt != nil {
		if cerr := q.listObjectsWithDelimiterStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listObjectsWithDelimiterStmt: %w", cerr)
		}
	}
	if q.listPendingNotificationJobsStmt != nil {
		if cerr := q.listPendingNotificationJobsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listPendingNotificationJobsStmt: %w", cerr)
		}
	}
	if q.objectExistsStmt != nil {
		if cerr := q.objectExistsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing objectExistsStmt: %w", cerr)
		}
	}
	if q.putBucketPolicyStmt != nil {
		if cerr := q.putBucketPolicyStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing putBucketPolicyStmt: %w", cerr)
		}
	}
	if q.updateNotificationStmt != nil {
		if cerr := q.updateNotificationStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateNotificationStmt: %w", cerr)
		}
	}
	if q.updateNotificationEnabledStmt != nil {
		if cerr := q.updateNotificationEnabledStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateNotificationEnabledStmt: %w", cerr)
		}
	}
	if q.updateNotificationJobStatusStmt != nil {
		if cerr := q.updateNotificationJobStatusStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateNotificationJobStatusStmt: %w", cerr)
		}
	}
	if q.updateObjectStmt != nil {
		if cerr := q.updateObjectStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateObjectStmt: %w", cerr)
		}
	}
	return err
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db                                   DBTX
	tx                                   *sql.Tx
	bucketExistsStmt                     *sql.Stmt
	bucketPolicyExistsStmt               *sql.Stmt
	copyObjectStmt                       *sql.Stmt
	countObjectsInBucketStmt             *sql.Stmt
	createBucketStmt                     *sql.Stmt
	createBucketTagStmt                  *sql.Stmt
	createEventStmt                      *sql.Stmt
	createNotificationStmt               *sql.Stmt
	createObjectStmt                     *sql.Stmt
	createObjectMetadataStmt             *sql.Stmt
	createObjectTagStmt                  *sql.Stmt
	deleteAllObjectTagsStmt              *sql.Stmt
	deleteBucketStmt                     *sql.Stmt
	deleteBucketPolicyStmt               *sql.Stmt
	deleteBucketTagStmt                  *sql.Stmt
	deleteBucketTagsStmt                 *sql.Stmt
	deleteNotificationStmt               *sql.Stmt
	deleteObjectStmt                     *sql.Stmt
	deleteObjectMetadataStmt             *sql.Stmt
	deleteObjectTagsStmt                 *sql.Stmt
	getBucketStmt                        *sql.Stmt
	getBucketPolicyStmt                  *sql.Stmt
	getBucketTagsStmt                    *sql.Stmt
	getNotificationStmt                  *sql.Stmt
	getObjectStmt                        *sql.Stmt
	getObjectByIDStmt                    *sql.Stmt
	getObjectIDStmt                      *sql.Stmt
	getObjectMetadataStmt                *sql.Stmt
	getObjectMetadataByObjectIDStmt      *sql.Stmt
	getObjectTagsStmt                    *sql.Stmt
	listBucketsStmt                      *sql.Stmt
	listBucketsFilteredStmt              *sql.Stmt
	listEnabledNotificationsByBucketStmt *sql.Stmt
	listEventsByBucketStmt               *sql.Stmt
	listNotificationsByBucketStmt        *sql.Stmt
	listNotificationsByEventTypeStmt     *sql.Stmt
	listObjectsStmt                      *sql.Stmt
	listObjectsWithDelimiterStmt         *sql.Stmt
	listPendingNotificationJobsStmt      *sql.Stmt
	objectExistsStmt                     *sql.Stmt
	putBucketPolicyStmt                  *sql.Stmt
	updateNotificationStmt               *sql.Stmt
	updateNotificationEnabledStmt        *sql.Stmt
	updateNotificationJobStatusStmt      *sql.Stmt
	updateObjectStmt                     *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:                                   tx,
		tx:                                   tx,
		bucketExistsStmt:                     q.bucketExistsStmt,
		bucketPolicyExistsStmt:               q.bucketPolicyExistsStmt,
		copyObjectStmt:                       q.copyObjectStmt,
		countObjectsInBucketStmt:             q.countObjectsInBucketStmt,
		createBucketStmt:                     q.createBucketStmt,
		createBucketTagStmt:                  q.createBucketTagStmt,
		createEventStmt:                      q.createEventStmt,
		createNotificationStmt:               q.createNotificationStmt,
		createObjectStmt:                     q.createObjectStmt,
		createObjectMetadataStmt:             q.createObjectMetadataStmt,
		createObjectTagStmt:                  q.createObjectTagStmt,
		deleteAllObjectTagsStmt:              q.deleteAllObjectTagsStmt,
		deleteBucketStmt:                     q.deleteBucketStmt,
		deleteBucketPolicyStmt:               q.deleteBucketPolicyStmt,
		deleteBucketTagStmt:                  q.deleteBucketTagStmt,
		deleteBucketTagsStmt:                 q.deleteBucketTagsStmt,
		deleteNotificationStmt:               q.deleteNotificationStmt,
		deleteObjectStmt:                     q.deleteObjectStmt,
		deleteObjectMetadataStmt:             q.deleteObjectMetadataStmt,
		deleteObjectTagsStmt:                 q.deleteObjectTagsStmt,
		getBucketStmt:                        q.getBucketStmt,
		getBucketPolicyStmt:                  q.getBucketPolicyStmt,
		getBucketTagsStmt:                    q.getBucketTagsStmt,
		getNotificationStmt:                  q.getNotificationStmt,
		getObjectStmt:                        q.getObjectStmt,
		getObjectByIDStmt:                    q.getObjectByIDStmt,
		getObjectIDStmt:                      q.getObjectIDStmt,
		getObjectMetadataStmt:                q.getObjectMetadataStmt,
		getObjectMetadataByObjectIDStmt:      q.getObjectMetadataByObjectIDStmt,
		getObjectTagsStmt:                    q.getObjectTagsStmt,
		listBucketsStmt:                      q.listBucketsStmt,
		listBucketsFilteredStmt:              q.listBucketsFilteredStmt,
		listEnabledNotificationsByBucketStmt: q.listEnabledNotificationsByBucketStmt,
		listEventsByBucketStmt:               q.listEventsByBucketStmt,
		listNotificationsByBucketStmt:        q.listNotificationsByBucketStmt,
		listNotificationsByEventTypeStmt:     q.listNotificationsByEventTypeStmt,
		listObjectsStmt:                      q.listObjectsStmt,
		listObjectsWithDelimiterStmt:         q.listObjectsWithDelimiterStmt,
		listPendingNotificationJobsStmt:      q.listPendingNotificationJobsStmt,
		objectExistsStmt:                     q.objectExistsStmt,
		putBucketPolicyStmt:                  q.putBucketPolicyStmt,
		updateNotificationStmt:               q.updateNotificationStmt,
		updateNotificationEnabledStmt:        q.updateNotificationEnabledStmt,
		updateNotificationJobStatusStmt:      q.updateNotificationJobStatusStmt,
		updateObjectStmt:                     q.updateObjectStmt,
	}
}
