// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql"
	"time"
)

type Bucket struct {
	Name      string    `json:"name"`
	Region    string    `json:"region"`
	CreatedAt time.Time `json:"created_at"`
}

type Object struct {
	ID                   int64          `json:"id"`
	BucketName           string         `json:"bucket_name"`
	Key                  string         `json:"key"`
	Data                 []byte         `json:"data"`
	Size                 int64          `json:"size"`
	ETag                 string         `json:"etag"`
	ContentType          string         `json:"content_type"`
	ContentEncoding      sql.NullString `json:"content_encoding"`
	ContentDisposition   sql.NullString `json:"content_disposition"`
	CacheControl         sql.NullString `json:"cache_control"`
	Expires              sql.NullTime   `json:"expires"`
	StorageClass         string         `json:"storage_class"`
	ServerSideEncryption sql.NullString `json:"server_side_encryption"`
	VersionID            sql.NullString `json:"version_id"`
	CreatedAt            time.Time      `json:"created_at"`
	UpdatedAt            time.Time      `json:"updated_at"`
}

type ObjectMetadatum struct {
	ID       int64  `json:"id"`
	ObjectID int64  `json:"object_id"`
	Key      string `json:"key"`
	Value    string `json:"value"`
}

type ObjectTag struct {
	ID       int64  `json:"id"`
	ObjectID int64  `json:"object_id"`
	Key      string `json:"key"`
	Value    string `json:"value"`
}
