// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"
)

type Bucket struct {
	Name      string    `json:"name"`
	Region    string    `json:"region"`
	CreatedAt time.Time `json:"created_at"`
}

type Event struct {
	ID         int64     `json:"id"`
	BucketName string    `json:"bucket_name"`
	ObjectID   int64     `json:"object_id"`
	EventType  string    `json:"event_type"`
	EventTime  time.Time `json:"event_time"`
}

type Notification struct {
	ID              int64          `json:"id"`
	BucketName      string         `json:"bucket_name"`
	EventType       string         `json:"event_type"`
	DestinationType string         `json:"destination_type"`
	DestinationArn  string         `json:"destination_arn"`
	FilterPrefix    sql.NullString `json:"filter_prefix"`
	FilterSuffix    sql.NullString `json:"filter_suffix"`
	Enabled         bool           `json:"enabled"`
	CreatedAt       time.Time      `json:"created_at"`
	UpdatedAt       time.Time      `json:"updated_at"`
}

type Object struct {
	ID                   int64          `json:"id"`
	BucketName           string         `json:"bucket_name"`
	Key                  string         `json:"key"`
	Data                 []byte         `json:"data"`
	Size                 int64          `json:"size"`
	ETag                 string         `json:"etag"`
	ContentType          string         `json:"content_type"`
	ContentEncoding      sql.NullString `json:"content_encoding"`
	ContentDisposition   sql.NullString `json:"content_disposition"`
	CacheControl         sql.NullString `json:"cache_control"`
	Expires              sql.NullTime   `json:"expires"`
	StorageClass         string         `json:"storage_class"`
	ServerSideEncryption sql.NullString `json:"server_side_encryption"`
	VersionID            sql.NullString `json:"version_id"`
	CreatedAt            time.Time      `json:"created_at"`
	UpdatedAt            time.Time      `json:"updated_at"`
}

type ObjectMetadatum struct {
	ID       int64  `json:"id"`
	ObjectID int64  `json:"object_id"`
	Key      string `json:"key"`
	Value    string `json:"value"`
}

type ObjectTag struct {
	ID       int64  `json:"id"`
	ObjectID int64  `json:"object_id"`
	Key      string `json:"key"`
	Value    string `json:"value"`
}
