// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: notification.sql

package db

import (
	"context"
	"database/sql"
)

const CreateNotification = `-- name: CreateNotification :one
INSERT INTO notifications (bucket_name, event_type, destination_type, destination_arn, filter_prefix, filter_suffix, enabled)
VALUES (?, ?, ?, ?, ?, ?, ?)
RETURNING id, bucket_name, event_type, destination_type, destination_arn, filter_prefix, filter_suffix, enabled, created_at, updated_at
`

type CreateNotificationParams struct {
	BucketName      string         `json:"bucket_name"`
	EventType       string         `json:"event_type"`
	DestinationType string         `json:"destination_type"`
	DestinationArn  string         `json:"destination_arn"`
	FilterPrefix    sql.NullString `json:"filter_prefix"`
	FilterSuffix    sql.NullString `json:"filter_suffix"`
	Enabled         bool           `json:"enabled"`
}

func (q *Queries) CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error) {
	row := q.queryRow(ctx, q.createNotificationStmt, CreateNotification,
		arg.BucketName,
		arg.EventType,
		arg.DestinationType,
		arg.DestinationArn,
		arg.FilterPrefix,
		arg.FilterSuffix,
		arg.Enabled,
	)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.BucketName,
		&i.EventType,
		&i.DestinationType,
		&i.DestinationArn,
		&i.FilterPrefix,
		&i.FilterSuffix,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const DeleteNotification = `-- name: DeleteNotification :exec
DELETE FROM notifications
WHERE id = ?
`

func (q *Queries) DeleteNotification(ctx context.Context, id int64) error {
	_, err := q.exec(ctx, q.deleteNotificationStmt, DeleteNotification, id)
	return err
}

const GetNotification = `-- name: GetNotification :one
SELECT id, bucket_name, event_type, destination_type, destination_arn, filter_prefix, filter_suffix, enabled, created_at, updated_at
FROM notifications
WHERE id = ?
`

func (q *Queries) GetNotification(ctx context.Context, id int64) (Notification, error) {
	row := q.queryRow(ctx, q.getNotificationStmt, GetNotification, id)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.BucketName,
		&i.EventType,
		&i.DestinationType,
		&i.DestinationArn,
		&i.FilterPrefix,
		&i.FilterSuffix,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const ListEnabledNotificationsByBucket = `-- name: ListEnabledNotificationsByBucket :many
SELECT id, bucket_name, event_type, destination_type, destination_arn, filter_prefix, filter_suffix, enabled, created_at, updated_at
FROM notifications
WHERE bucket_name = ? AND enabled = 1
ORDER BY created_at DESC
`

func (q *Queries) ListEnabledNotificationsByBucket(ctx context.Context, bucketName string) ([]Notification, error) {
	rows, err := q.query(ctx, q.listEnabledNotificationsByBucketStmt, ListEnabledNotificationsByBucket, bucketName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Notification{}
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.BucketName,
			&i.EventType,
			&i.DestinationType,
			&i.DestinationArn,
			&i.FilterPrefix,
			&i.FilterSuffix,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListNotificationsByBucket = `-- name: ListNotificationsByBucket :many
SELECT id, bucket_name, event_type, destination_type, destination_arn, filter_prefix, filter_suffix, enabled, created_at, updated_at
FROM notifications
WHERE bucket_name = ?
ORDER BY created_at DESC
`

func (q *Queries) ListNotificationsByBucket(ctx context.Context, bucketName string) ([]Notification, error) {
	rows, err := q.query(ctx, q.listNotificationsByBucketStmt, ListNotificationsByBucket, bucketName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Notification{}
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.BucketName,
			&i.EventType,
			&i.DestinationType,
			&i.DestinationArn,
			&i.FilterPrefix,
			&i.FilterSuffix,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListNotificationsByEventType = `-- name: ListNotificationsByEventType :many
SELECT id, bucket_name, event_type, destination_type, destination_arn, filter_prefix, filter_suffix, enabled, created_at, updated_at
FROM notifications
WHERE bucket_name = ? AND event_type = ? AND enabled = 1
`

type ListNotificationsByEventTypeParams struct {
	BucketName string `json:"bucket_name"`
	EventType  string `json:"event_type"`
}

func (q *Queries) ListNotificationsByEventType(ctx context.Context, arg ListNotificationsByEventTypeParams) ([]Notification, error) {
	rows, err := q.query(ctx, q.listNotificationsByEventTypeStmt, ListNotificationsByEventType, arg.BucketName, arg.EventType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Notification{}
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.BucketName,
			&i.EventType,
			&i.DestinationType,
			&i.DestinationArn,
			&i.FilterPrefix,
			&i.FilterSuffix,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListPendingNotificationJobs = `-- name: ListPendingNotificationJobs :many
SELECT
    notification_jobs.id, notification_jobs.event_id, notification_jobs.notification_id, notification_jobs.status, notification_jobs.attempts, notification_jobs.error_message, notification_jobs.created_at, notification_jobs.updated_at,
    events.id, events.bucket_name, events.object_id, events.event_type, events.event_time,
    notifications.id, notifications.bucket_name, notifications.event_type, notifications.destination_type, notifications.destination_arn, notifications.filter_prefix, notifications.filter_suffix, notifications.enabled, notifications.created_at, notifications.updated_at
FROM notification_jobs
JOIN events ON notification_jobs.event_id = events.id
JOIN notifications ON notification_jobs.notification_id = notifications.id
WHERE notification_jobs.status = 'pending'
ORDER BY notification_jobs.created_at ASC
`

type ListPendingNotificationJobsRow struct {
	NotificationJob NotificationJob `json:"notification_job"`
	Event           Event           `json:"event"`
	Notification    Notification    `json:"notification"`
}

func (q *Queries) ListPendingNotificationJobs(ctx context.Context) ([]ListPendingNotificationJobsRow, error) {
	rows, err := q.query(ctx, q.listPendingNotificationJobsStmt, ListPendingNotificationJobs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPendingNotificationJobsRow{}
	for rows.Next() {
		var i ListPendingNotificationJobsRow
		if err := rows.Scan(
			&i.NotificationJob.ID,
			&i.NotificationJob.EventID,
			&i.NotificationJob.NotificationID,
			&i.NotificationJob.Status,
			&i.NotificationJob.Attempts,
			&i.NotificationJob.ErrorMessage,
			&i.NotificationJob.CreatedAt,
			&i.NotificationJob.UpdatedAt,
			&i.Event.ID,
			&i.Event.BucketName,
			&i.Event.ObjectID,
			&i.Event.EventType,
			&i.Event.EventTime,
			&i.Notification.ID,
			&i.Notification.BucketName,
			&i.Notification.EventType,
			&i.Notification.DestinationType,
			&i.Notification.DestinationArn,
			&i.Notification.FilterPrefix,
			&i.Notification.FilterSuffix,
			&i.Notification.Enabled,
			&i.Notification.CreatedAt,
			&i.Notification.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const UpdateNotification = `-- name: UpdateNotification :exec
UPDATE notifications
SET event_type = ?, destination_type = ?, destination_arn = ?, filter_prefix = ?, filter_suffix = ?, enabled = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type UpdateNotificationParams struct {
	EventType       string         `json:"event_type"`
	DestinationType string         `json:"destination_type"`
	DestinationArn  string         `json:"destination_arn"`
	FilterPrefix    sql.NullString `json:"filter_prefix"`
	FilterSuffix    sql.NullString `json:"filter_suffix"`
	Enabled         bool           `json:"enabled"`
	ID              int64          `json:"id"`
}

func (q *Queries) UpdateNotification(ctx context.Context, arg UpdateNotificationParams) error {
	_, err := q.exec(ctx, q.updateNotificationStmt, UpdateNotification,
		arg.EventType,
		arg.DestinationType,
		arg.DestinationArn,
		arg.FilterPrefix,
		arg.FilterSuffix,
		arg.Enabled,
		arg.ID,
	)
	return err
}

const UpdateNotificationEnabled = `-- name: UpdateNotificationEnabled :exec
UPDATE notifications
SET enabled = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type UpdateNotificationEnabledParams struct {
	Enabled bool  `json:"enabled"`
	ID      int64 `json:"id"`
}

func (q *Queries) UpdateNotificationEnabled(ctx context.Context, arg UpdateNotificationEnabledParams) error {
	_, err := q.exec(ctx, q.updateNotificationEnabledStmt, UpdateNotificationEnabled, arg.Enabled, arg.ID)
	return err
}

const UpdateNotificationJobStatus = `-- name: UpdateNotificationJobStatus :exec
UPDATE notification_jobs
SET status = ?,
    attempts = ?,
    error_message = ?,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type UpdateNotificationJobStatusParams struct {
	Status       string         `json:"status"`
	Attempts     int64          `json:"attempts"`
	ErrorMessage sql.NullString `json:"error_message"`
	ID           int64          `json:"id"`
}

func (q *Queries) UpdateNotificationJobStatus(ctx context.Context, arg UpdateNotificationJobStatusParams) error {
	_, err := q.exec(ctx, q.updateNotificationJobStatusStmt, UpdateNotificationJobStatus,
		arg.Status,
		arg.Attempts,
		arg.ErrorMessage,
		arg.ID,
	)
	return err
}
