// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"context"
)

type Querier interface {
	BucketExists(ctx context.Context, name string) (bool, error)
	BucketPolicyExists(ctx context.Context, bucketName string) (bool, error)
	CopyObject(ctx context.Context, arg CopyObjectParams) (CopyObjectRow, error)
	CountObjectsInBucket(ctx context.Context, bucketName string) (int64, error)
	CreateBucket(ctx context.Context, arg CreateBucketParams) error
	CreateBucketTag(ctx context.Context, arg CreateBucketTagParams) error
	CreateEvent(ctx context.Context, arg CreateEventParams) (Event, error)
	CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error)
	CreateObject(ctx context.Context, arg CreateObjectParams) (CreateObjectRow, error)
	// Object Metadata queries
	CreateObjectMetadata(ctx context.Context, arg CreateObjectMetadataParams) error
	// Object Tags queries
	CreateObjectTag(ctx context.Context, arg CreateObjectTagParams) error
	DeleteAllObjectTags(ctx context.Context, objectID int64) error
	DeleteBucket(ctx context.Context, name string) error
	DeleteBucketPolicy(ctx context.Context, bucketName string) error
	DeleteBucketTag(ctx context.Context, arg DeleteBucketTagParams) error
	DeleteBucketTags(ctx context.Context, bucketName string) error
	DeleteNotification(ctx context.Context, id int64) error
	DeleteObject(ctx context.Context, arg DeleteObjectParams) error
	DeleteObjectMetadata(ctx context.Context, objectID int64) error
	DeleteObjectTags(ctx context.Context, objectID int64) error
	GetBucket(ctx context.Context, name string) (Bucket, error)
	GetBucketPolicy(ctx context.Context, bucketName string) (GetBucketPolicyRow, error)
	GetBucketTags(ctx context.Context, bucketName string) ([]GetBucketTagsRow, error)
	GetNotification(ctx context.Context, id int64) (Notification, error)
	GetObject(ctx context.Context, arg GetObjectParams) (Object, error)
	GetObjectByID(ctx context.Context, id int64) (GetObjectByIDRow, error)
	GetObjectID(ctx context.Context, arg GetObjectIDParams) (int64, error)
	GetObjectMetadata(ctx context.Context, arg GetObjectMetadataParams) (GetObjectMetadataRow, error)
	GetObjectMetadataByObjectID(ctx context.Context, objectID int64) ([]GetObjectMetadataByObjectIDRow, error)
	GetObjectTags(ctx context.Context, objectID int64) ([]GetObjectTagsRow, error)
	ListBuckets(ctx context.Context) ([]Bucket, error)
	ListBucketsFiltered(ctx context.Context, arg ListBucketsFilteredParams) ([]Bucket, error)
	ListEnabledNotificationsByBucket(ctx context.Context, bucketName string) ([]Notification, error)
	ListEventsByBucket(ctx context.Context, arg ListEventsByBucketParams) ([]Event, error)
	ListNotificationsByBucket(ctx context.Context, bucketName string) ([]Notification, error)
	ListNotificationsByEventType(ctx context.Context, arg ListNotificationsByEventTypeParams) ([]Notification, error)
	ListObjects(ctx context.Context, arg ListObjectsParams) ([]ListObjectsRow, error)
	ListObjectsWithDelimiter(ctx context.Context, arg ListObjectsWithDelimiterParams) ([]ListObjectsWithDelimiterRow, error)
	ListPendingNotificationJobs(ctx context.Context) ([]ListPendingNotificationJobsRow, error)
	ObjectExists(ctx context.Context, arg ObjectExistsParams) (bool, error)
	PutBucketPolicy(ctx context.Context, arg PutBucketPolicyParams) error
	UpdateNotification(ctx context.Context, arg UpdateNotificationParams) error
	UpdateNotificationEnabled(ctx context.Context, arg UpdateNotificationEnabledParams) error
	UpdateNotificationJobStatus(ctx context.Context, arg UpdateNotificationJobStatusParams) error
	UpdateObject(ctx context.Context, arg UpdateObjectParams) error
}

var _ Querier = (*Queries)(nil)
