// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"context"
)

type Querier interface {
	BucketExists(ctx context.Context, name string) (bool, error)
	CopyObject(ctx context.Context, arg CopyObjectParams) (CopyObjectRow, error)
	CountObjectsInBucket(ctx context.Context, bucketName string) (int64, error)
	CreateBucket(ctx context.Context, arg CreateBucketParams) error
	CreateObject(ctx context.Context, arg CreateObjectParams) (CreateObjectRow, error)
	// Object Metadata queries
	CreateObjectMetadata(ctx context.Context, arg CreateObjectMetadataParams) error
	// Object Tags queries
	CreateObjectTag(ctx context.Context, arg CreateObjectTagParams) error
	DeleteAllObjectTags(ctx context.Context, objectID int64) error
	DeleteBucket(ctx context.Context, name string) error
	DeleteObject(ctx context.Context, arg DeleteObjectParams) error
	DeleteObjectMetadata(ctx context.Context, objectID int64) error
	DeleteObjectTags(ctx context.Context, objectID int64) error
	GetBucket(ctx context.Context, name string) (Bucket, error)
	GetObject(ctx context.Context, arg GetObjectParams) (Object, error)
	GetObjectID(ctx context.Context, arg GetObjectIDParams) (int64, error)
	GetObjectMetadata(ctx context.Context, arg GetObjectMetadataParams) (GetObjectMetadataRow, error)
	GetObjectMetadataByObjectID(ctx context.Context, objectID int64) ([]GetObjectMetadataByObjectIDRow, error)
	GetObjectTags(ctx context.Context, objectID int64) ([]GetObjectTagsRow, error)
	ListBuckets(ctx context.Context) ([]Bucket, error)
	ListObjects(ctx context.Context, arg ListObjectsParams) ([]ListObjectsRow, error)
	ListObjectsWithDelimiter(ctx context.Context, arg ListObjectsWithDelimiterParams) ([]ListObjectsWithDelimiterRow, error)
	ObjectExists(ctx context.Context, arg ObjectExistsParams) (bool, error)
	UpdateObject(ctx context.Context, arg UpdateObjectParams) error
}

var _ Querier = (*Queries)(nil)
